# Generated by Django 4.1.3 on 2023-01-07 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_managers_organizationchanneluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationchanneluser',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationchanneluser',
            name='organization_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_channel_users', to='chat.organizationchannel'),
            preserve_default=False,
        ),
    ]
